# Generated by Django 2.1.5 on 2020-10-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nikename',
            new_name='nickname',
        ),
    ]
